updated pre-commit hook
updated one of the error messages, and made it return a non-zero status
code if there's an issue

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,25 +1,28 @@
-!#/bin/bash
+#!/bin/bash
 
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
+# Initialize a flag for failure
+exit_code=0
 
-# Format all files
-# api
-# TODO: check eslint for errors
+# Format all files in the api folder
 prettier ./api --write --ignore-path .gitignore --log-level warn --ignore-unknown
 prettier_exit_code=$?
 
 if [ $prettier_exit_code -ne 0 ]; then
   echo "❌ Error formatting files in api server. Please fix any issues"
+  exit_code=1
 fi
 
-# mobile app
+# Run Dart analysis on the mobile app
 dart analyze ./app
 dart_analyze_exit_code=$?
 
 if [ $dart_analyze_exit_code -ne 0 ]; then
-  echo "❌ Error formatting files in the app. Please fix any issues first"
+  echo "❌ Error found in the app. Please fix any issues first"
+  exit_code=1
 fi
 
+# Format all files in the mobile app
 dart format ./app
+
+# Exit with the appropriate code (0 or 1)
+exit $exit_code
